#注册中心register的端口号
server:
  port: 9200
eureka:
  server:
    #关闭自我保护机制
    enable-self-preservation: false
    #设置清理间隔，默认60*1000 单位：毫秒
    eviction-interval-timer-in-ms: 4000
  client:
    #是否到eureka服务器中抓取注册信息
    fetch-registry: false
    #生命是否将自己的信息注册到eureka服务器，默认值为true
    register-with-eureka: false
    #向register01服务注册中心注册自己
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9100/eureka/
  instance:
    hostname: localhost
#注册中心起别名
spring:
  application:
    name: server-register02